name: frontend-push

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-push.yml'

jobs:
  frontend-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd frontend
          yarn install --immutable --immutable-cache
          yarn build

      - name: Deploy to juliushenke.com
        if: github.ref_name == 'master' || github.ref_name == 'main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JULIUSHENKE_96CE3 }}'
          channelId: live
          projectId: juliushenke-96ce3